services:
  # Database Service
  - type: pserv
    name: event-management-db
    env: docker
    plan: starter
    disk:
      name: postgres
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        value: event_management

  # Backend Service
  - type: web
    name: event-management-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: event-management-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: FRONTEND_URL
        value: https://event-management-frontend.onrender.com
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_SERVER
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false

  # Frontend Service
  - type: web
    name: event-management-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: npm install && npm run build
    startCommand: nginx -g 'daemon off;'
    envVars:
      - key: REACT_APP_API_URL
        value: https://event-management-api.onrender.com 